const monitorBrowserModel = {
    id: 0,
    browserVersion: '',
    browserVersionNumber: '',
    browserName: '',
    os: '',
    netType: '',
    language: '',
    platform: '',
    model: '',
    domain: '',
    url: '',
    title: '',
    referrer: '',
    lastModified: '',
    cookie: '',
    characterSet: '',
    screenHeight: '',
    screenWidth: '',
    colorDepth: '',
    devicePixelRatio: '',
    performance: '',
    dnsTime: '',
    tcpTime: '',
    firstPaintTime: '',
    FirstContentfulPaintTime: '',
    domRenderTime: '',
    loadTime: '',
    resourceInfo: '',
    ip: '',
    time: new Date().getTime().toString()
}

module.exports = monitorBrowserModel;